### ISSUE TITLE
Dependabot opens pull request for projects of they have outdated package or dependency. The problem is it opens PR such with title "chore:" is there a way to change the title to feat or fix depending on package or module source. Investage what options are avtto change the PR title from chore to feat or fix. Basically feat or fix depends on conventional commit.

### ISSUE THREAD

**Issue by nguyentrungduc134** [nguyentrungduc134/dependabot_title_changes_workflow#1]
Yes, you can customize the title of pull requests created by Dependabot by configuring it to follow conventional commit standards like `feat`, `fix`, or `chore` based on the type of update.

Here's how you can approach this:

### 1. **Use Dependabot's `versioning-strategy`**
Dependabot uses a versioning strategy that can be configured in your `dependabot.yml` file. While this doesn't directly change the title, it helps you ensure that updates are following a predictable versioning format.

However, to **change the PR title**, you will need to combine a few strategies:

### 2. **Dependabot Commit Message Format (with `versioning-strategy`)**
You can use the `versioning-strategy` option in your `dependabot.yml` file to control how dependencies are updated. While this doesn’t change PR titles directly, it’s a good step toward aligning your dependency updates with conventional commit principles.

Example of `dependabot.yml`:

```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"
```

The versioning strategy will help you decide whether you want to make "major", "minor", or "patch" updates, which can then be mapped to commit types like `feat`, `fix`, etc.

### 3. **GitHub Actions for PR Title Customization**
You can create a GitHub Action that triggers when a Dependabot PR is created and automatically updates the PR title based on the dependency type or changes.

Here's an example GitHub Action that would check for the type of update and update the title based on conventional commit types:

#### Example `.github/workflows/dependabot-pr-title.yml`

```yaml
name: Set Dependabot PR Title

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  set-pr-title:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check if PR is created by Dependabot
      if: github.actor == 'dependabot[bot]'
      run: |
        PR_TITLE="chore: update dependencies"
        
        # Check if the PR is for a major update
        if grep -q 'BREAKING CHANGE' <<<"${{ github.event.pull_request.body }}"; then
          PR_TITLE="feat: update dependency"
        fi
        
        # Check if the PR is a patch update (based on conventional commit strategy)
        if grep -q 'fix' <<<"${{ github.event.pull_request.body }}"; then
          PR_TITLE="fix: update dependency"
        fi

        # Update the PR title
        curl -X PATCH \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"title": "'$PR_TITLE'"}' \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}"
```

### 4. **How It Works:**
- The GitHub Action triggers when a new PR is opened or synchronized (updated).
- It checks if the PR was created by Dependabot.
- Depending on the contents of the PR (for instance, if it contains `BREAKING CHANGE` or the update is a patch), it updates the title to `feat:`, `fix:`, or `chore:`.
- The action then uses GitHub’s API to patch the PR title.

### 5. **Advanced Configuration with Commit Messages:**
For more fine-grained control, you can inspect the commit messages in the PR and use them to classify the type of update. You can parse the commit messages for keywords such as `fix`, `feat`, or `chore`, and use that to determine the PR title.

---

### 6. **Alternative Approach: Custom GitHub App**
If you want a more robust solution, you could write a custom GitHub app that listens for pull request events and modifies the title based on conventional commit standards. This would give you the most flexibility.

---

This way, you can automate the process of changing PR titles according to the conventional commit message type, making your version control process more aligned with best practices. Let me know if you need further assistance on this!
