### ISSUE TITLE
"message": "Resource not accessible by integration",
  "documentation_url": "https://docs.github.com/rest/pulls/pulls#update-a-pull-request",

### ISSUE THREAD

**Issue by nguyentrungduc134** [nguyentrungduc134/dependabot_title_changes_workflow#13]
The error **"Resource not accessible by integration"** happens because `GITHUB_TOKEN` used in GitHub Actions **does not have permission to update Dependabot PRs by default**. GitHub restricts workflow permissions to prevent unauthorized modifications to PRs created by bots like Dependabot.

---

### ✅ **Fix: Enable `GITHUB_TOKEN` with Write Permissions**
By default, `GITHUB_TOKEN` has **read-only** permissions for Dependabot PRs. You need to explicitly enable **write permissions** in your GitHub Actions workflow.

#### **1️⃣ Update `permissions` in the Workflow**
Modify your GitHub Actions workflow (`.github/workflows/update-pr-title.yml`) to explicitly grant write access to pull requests:

```yaml
name: Update Dependabot PR Title

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited

permissions:
  pull-requests: write  # ✅ Allow PR title updates

jobs:
  update-title:
    if: github.actor == 'dependabot[bot]'  # ✅ Run only for Dependabot PRs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update PR Title Based on Module Update
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"

          # Check if the PR contains a Terraform module update
          if [[ "$PR_TITLE" =~ "terraform-aws-modules/vpc/aws" ]]; then
            NEW_TITLE="fix: Update terraform-aws-modules/vpc/aws module from old to new version"
          else
            NEW_TITLE="chore: Update dependencies"
          fi

          echo "Updating PR title to: $NEW_TITLE"

          # Update PR title using GitHub API
          curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"title": "'"$NEW_TITLE"'"}' \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}"
```

---

#### **2️⃣ Enable Workflow Permissions in Repository Settings**
If the error persists, check your repository settings:

1. **Go to your GitHub repository → `Settings`**
2. **Click on `Actions` (left sidebar)**
3. Scroll down to **"Workflow permissions"**
4. **Select** ✅ `Read and write permissions`
5. **Save changes**

---

### 🔄 **Alternative: Use a Personal Access Token (PAT)**
If GitHub still blocks PR title updates, you can use a **Personal Access Token (PAT)** instead of `GITHUB_TOKEN`.

1. **Generate a PAT** with `repo` and `pull_requests` permissions:
   - Go to [GitHub Token Settings](https://github.com/settings/tokens)
   - Create a new token with `repo` and `pull_requests` scopes.
   - Copy the token.

2. **Add the token to GitHub Secrets**:
   - Go to **Repository Settings** → **Secrets and variables** → **Actions**
   - Add a new secret:  
     - **Name:** `PERSONAL_ACCESS_TOKEN`
     - **Value:** _(Paste the PAT token)_

3. **Modify the Workflow to Use the PAT**:
   ```yaml
   - name: Update PR Title Using PAT
     run: |
       curl -X PATCH -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
         -H "Accept: application/vnd.github.v3+json" \
         -d '{"title": "'"$NEW_TITLE"'"}' \
         "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}"
   ```

---

### ✅ **Final Solution Recap**
✔ **Step 1:** Add `permissions: pull-requests: write` in the workflow  
✔ **Step 2:** Enable **"Read and write permissions"** in repo settings  
✔ **Step 3 (Optional):** Use a **PAT** if GitHub still blocks updates  

---

### 🚀 **Now, Dependabot PR Titles Will Be Updated!**
Would you like me to test this setup further or add more filtering for different dependencies?
