### ISSUE TITLE
it works fine before add
permissions:
  pull-requests: write  # ✅ Allow PR title updates

### ISSUE THREAD

**Issue by nguyentrungduc134** [nguyentrungduc134/dependabot_title_changes_workflow#14]
Since your workflow was working fine **before adding**:  

```yaml
permissions:
  pull-requests: write  # ✅ Allow PR title updates
```

It suggests that modifying the permissions might have affected how `GITHUB_TOKEN` is being used.  

---

### ✅ **Fix: Explicitly Set All Required Permissions**  

Try **explicitly defining multiple permissions** instead of just `pull-requests: write`:  

```yaml
permissions:
  contents: read  # ✅ Allow checking out the repo
  pull-requests: write  # ✅ Allow updating PR titles
```

### **Why This Works**  
- **`contents: read`** → Ensures that the repository can still be cloned  
- **`pull-requests: write`** → Allows the PR title updates  

---

### 🔄 **Alternative Fix: Remove `permissions` and Use a PAT**
If the issue persists, try **removing the `permissions:` block** and using a **Personal Access Token (PAT)** instead:

1. **Create a PAT with `repo` and `pull_requests` scopes**  
   - Go to [GitHub Token Settings](https://github.com/settings/tokens)  
   - Generate a token with these scopes:  
     ✅ `repo` (full access)  
     ✅ `pull_requests`  

2. **Add the PAT to GitHub Secrets**  
   - Go to **Repository Settings** → `Secrets and Variables` → `Actions`  
   - Add a new secret:  
     - **Name:** `GH_PAT`  
     - **Value:** _(Paste the PAT token)_  

3. **Update Your Workflow to Use the PAT**  

```yaml
jobs:
  update-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}  # ✅ Use PAT instead of GITHUB_TOKEN
```

---

### 🚀 **Final Steps**  
- **Try `permissions: contents: read, pull-requests: write` first.**  
- If that **doesn’t work**, switch to using a **PAT (`GH_PAT`)**.  
- Then **rerun your workflow** in GitHub Actions.  

Let me know if you need more help! 😊
