### ISSUE TITLE
can it take from dependabot title

### ISSUE THREAD

**Issue by nguyentrungduc134** [nguyentrungduc134/dependabot_title_changes_workflow#28]
Yes! **Release Please can take the title from Dependabot PRs** if the PR title follows **Conventional Commits** (`feat:`, `fix:`, etc.).  

#### **1️⃣ Configure Dependabot to Use Conventional Commit Titles**  
Modify `.github/dependabot.yml` to enforce `feat:` or `fix:` prefixes in PR titles:  

```yaml
version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "feat"
      include: "scope"
```
👉 This ensures **Dependabot PRs start with `feat:` or `fix:`** instead of `chore:`.  

---

#### **2️⃣ Configure Release Please to Use PR Titles**  
Modify `.github/release-please-config.json` (or `.release-please-manifest.json`):  

```json
{
  "branches": {
    "main": {
      "changelog-type": "github",
      "pull-request-title-pattern": "{{title}}"
    }
  }
}
```
👉 This makes **Release Please take PR titles directly** instead of generating `"chore: release X.Y.Z"`.

---

#### **3️⃣ (Optional) Automate PR Title Correction via GitHub Actions**  
If Dependabot PR titles are **inconsistent**, your existing GitHub Action (that modifies PR titles) will still work. **Release Please will then use the corrected title**.

---

### **Final Outcome**
✅ **Release PR titles will match Dependabot PR titles**  
✅ **No more** `"chore: release X.Y.Z"`  
✅ **Changelogs will reflect meaningful updates**  

Let me know if you need tweaks! 🚀
