### ISSUE TITLE
give me some example repos for this case:
One use case is, if one terraform module is dependentnt in another module and if that module is updated with new release then the dependent module PR opened by dependabot should be feat or fix.

### ISSUE THREAD

**Issue by nguyentrungduc134** [nguyentrungduc134/dependabot_title_changes_workflow#4]
Finding public repositories that specifically configure Dependabot to label pull requests (PRs) as `feat` or `fix` based on updates to dependent Terraform modules is challenging, as such configurations are often customized and may not be publicly documented. However, I can guide you on how to set up such a system:

**1. Configure Dependabot for Terraform Modules:**
To enable Dependabot to monitor and update Terraform module dependencies, add a `.github/dependabot.yml` file to your repository with the following content:

```yaml
version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
```

This configuration instructs Dependabot to check for updates to Terraform modules daily and to prefix commit messages with `chore`.

**2. Use GitHub Actions to Modify PR Titles Based on Content:**
Since Dependabot does not natively support dynamic PR titles based on the nature of the update, you can implement a GitHub Action that triggers upon the creation of a Dependabot PR. This action can inspect the PR's content and adjust the title accordingly.

Here's an example workflow (`.github/workflows/update-pr-title.yml`):

```yaml
name: Update Dependabot PR Title
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
jobs:
  update-pr-title:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Analyze PR Content and Update Title
        run: |
          npm install -g conventional-commits-parser
          PR_BODY=$(jq -r '.pull_request.body' "$GITHUB_EVENT_PATH")
          PR_TITLE=$(jq -r '.pull_request.title' "$GITHUB_EVENT_PATH")
          if echo "$PR_BODY" | grep -iqE 'security|cve|bug'; then
            PREFIX="fix"
          elif echo "$PR_BODY" | grep -iqE 'breaking change|new feature|major update'; then
            PREFIX="feat"
          else
            PREFIX="chore"
          fi
          NEW_TITLE="$PREFIX: ${PR_TITLE#*: }"
          echo "New PR Title: $NEW_TITLE"
          gh pr edit "$GITHUB_REF" --title "$NEW_TITLE"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

This workflow performs the following steps:

- **Triggers** on the creation or synchronization of a PR to the main branch by Dependabot.
- **Sets up Node.js** to use the `conventional-commits-parser` package.
- **Analyzes** the PR body for keywords indicating the nature of the update.
- **Determines** the appropriate prefix (`fix`, `feat`, or `chore`) based on the content.
- **Updates** the PR title with the new prefix.

**3. Implement Semantic Release for Automated Versioning:**
To automate releases based on the commit messages, integrate a tool like `semantic-release` into your CI/CD pipeline. This tool can interpret the conventional commit messages (`feat`, `fix`, `chore`) to determine the type of version bump (major, minor, patch) and handle the release process accordingly.

By combining Dependabot for dependency updates, a GitHub Action to adjust PR titles based on content, and `semantic-release` for automated versioning, you can create a workflow where updates to Terraform modules are appropriately categorized and released.

For further reading on configuring Dependabot and automating releases for Terraform modules, consider these resources:

- citeturn0search0
- citeturn0search7
- citeturn0search9

These articles provide insights into using Dependabot with Terraform modules and automating releases using conventional commits.
