### ISSUE TITLE
what if module use directly in the tf file not in modules folder (from registry)

### ISSUE THREAD

**Issue by nguyentrungduc134** [nguyentrungduc134/dependabot_title_changes_workflow#5]
If a Terraform module is used **directly in the `.tf` file** (not within a `modules/` folder but instead sourced directly from a registry or other location), you can still handle the PR titles and updates similarly. The key difference is that you're referencing the module directly in your `main.tf` (or equivalent) instead of using a local module structure.

Here’s how you can still detect updates and adjust the PR title:

### Example: Using Remote Modules Directly in the `.tf` File

Let's say you're using a module from the Terraform Registry directly in your `main.tf` like this:

```hcl
module "vpc" {
  source = "terraform-aws-modules/vpc/aws"
  version = "3.0.0"
  name    = "my-vpc"
  cidr    = "10.0.0.0/16"
}
```

This is an example of a **remote module** used directly in your Terraform file, not in a `modules/` directory.

### 1. **Dependabot Configuration**

Dependabot will still open PRs when the version of the module changes, or when there’s a newer release in the registry. In this case, you can still use the `.github/dependabot.yml` configuration file to instruct Dependabot to check for updates in your Terraform modules:

```yaml
version: 2
updates:
  - package-ecosystem: terraform
    directory: "/"  # The root directory where the `main.tf` file is located
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
```

### 2. **GitHub Action to Change PR Title Based on Module Update**

You can still use the same approach as before with a GitHub Action to change the PR title depending on the module that is updated. In this case, you would likely look for the **module name** in the PR body or title.

Create a `.github/workflows/update-pr-title.yml` file with the following content:

```yaml
name: Update PR Title Based on Module Update

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  update-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set PR title based on module update
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          
          # Check if module `vpc` is mentioned in the PR title (this could be updated based on module name)
          if [[ "$PR_TITLE" =~ "terraform-aws-modules/vpc/aws" ]]; then
            NEW_TITLE="fix: Update terraform-aws-modules/vpc/aws module"
          else
            NEW_TITLE="chore: Update dependencies"
          fi

          echo "New PR title: $NEW_TITLE"
          
          # Update PR title using GitHub API
          curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"title": "'"$NEW_TITLE"'"}' \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}"
```

### Explanation:
1. **Detecting Module Updates:**
   - The GitHub Action checks the PR title to see if it contains the name of the module (e.g., `terraform-aws-modules/vpc/aws`).
   - If the module name is found, it updates the PR title to `fix:`.
   - If the module name is not found, the default PR title will be set to `chore:`, or any other default you specify.

2. **PR Title Update:**
   - The GitHub Action makes an API call to GitHub to change the PR title to the appropriate prefix (`fix:` or `chore:`) depending on the module being updated.

### 3. **Example Workflow in Action:**
1. **Dependabot opens a PR**: The title might look like `Bump terraform-aws-modules/vpc/aws from 2.0.0 to 3.0.0`.
2. **GitHub Action is triggered**: The action checks if `terraform-aws-modules/vpc/aws` is in the title.
3. **PR Title is updated**: If the module is `vpc`, the PR title is updated to `fix: Update terraform-aws-modules/vpc/aws module`.

### 4. **Handling Multiple Modules**:
If you are using multiple modules from the registry in the same `main.tf` file (or equivalent), you can expand the GitHub Action to check for each module and modify the PR title accordingly.

For example, you can check for `vpc`, `s3`, or any other module name and adjust the PR title to reflect the update appropriately.

```yaml
if [[ "$PR_TITLE" =~ "terraform-aws-modules/vpc/aws" ]]; then
    NEW_TITLE="fix: Update terraform-aws-modules/vpc/aws module"
elif [[ "$PR_TITLE" =~ "terraform-aws-modules/s3-bucket/aws" ]]; then
    NEW_TITLE="fix: Update terraform-aws-modules/s3-bucket/aws module"
else
    NEW_TITLE="chore: Update dependencies"
fi
```

### 5. **Test and Validate:**
Once you've set everything up:
- Dependabot will open PRs for module updates.
- The GitHub Action will detect the module update and adjust the PR title accordingly.

---

### Final Thoughts:
This approach allows you to update the PR titles based on which remote module is updated, even if the module is not in the `modules/` folder but is sourced directly in your `main.tf` file. By using GitHub Actions, you can automate the title change process based on the module name or other conditions you define.

Would you like assistance with testing this setup or refining the conditions for specific modules?
