### ISSUE TITLE
Can you filter pr by dependabot[bot] only

### ISSUE THREAD

**Issue by nguyentrungduc134** [nguyentrungduc134/dependabot_title_changes_workflow#9]
Yes, you can filter PRs created **only** by `dependabot[bot]` in a GitHub Action using conditions in the workflow file.

### **Method 1: Using `github.actor` in Workflow**  
Modify your workflow file to run **only if the PR is created by Dependabot**:

```yaml
name: Update Dependabot PR Title

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited

jobs:
  update-title:
    if: github.actor == 'dependabot[bot]'  # Run only for Dependabot PRs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update PR Title Based on Module Update
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"

          # Check if the PR contains a Terraform module update
          if [[ "$PR_TITLE" =~ "terraform-aws-modules/vpc/aws" ]]; then
            NEW_TITLE="fix: Update terraform-aws-modules/vpc/aws module from old to new version"
          else
            NEW_TITLE="chore: Update dependencies"
          fi

          echo "Updating PR title to: $NEW_TITLE"

          # Update the PR title using GitHub API
          curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"title": "'"$NEW_TITLE"'"}' \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}"
```

### **How This Works**
1. **Filters PRs by `github.actor == 'dependabot[bot]'`** → Ensures only Dependabot-created PRs trigger the job.
2. **Checks if a Terraform module update is in the PR title**.
3. **Updates the PR title dynamically using the GitHub API**.

### **Method 2: Filter Dependabot PRs Using `jq`**
If you need more complex filtering within a script, you can use `jq` to check the PR author:

```bash
PR_AUTHOR=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
  "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | jq -r '.user.login')

if [[ "$PR_AUTHOR" == "dependabot[bot]" ]]; then
  echo "This PR is from Dependabot."
  # Run title update logic
else
  echo "Skipping PR - Not from Dependabot."
fi
```

Would you like additional filtering, such as filtering by specific dependencies or Terraform modules?
